services:
  frontend:
    image: ghcr.io/rdemora2/front-site--tivix-performance-tracker:latest
    container_name: app-performance-tracker-frontend
    restart: unless-stopped
    networks:
      - web
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.tracker-frontend.rule=Host(`performancetracker.tivix.com.br`) || Host(`performance.valiantgroup.com.br`)"

      - "traefik.http.routers.tracker-frontend.entrypoints=websecure"
      - "traefik.http.routers.tracker-frontend.tls.certresolver=myresolver"
      - "traefik.http.services.tracker-frontend.loadbalancer.server.port=80"

  # --- Backend ---
  # Deixaremos este espa√ßo preparado para quando migrarmos o backend.
  # backend:
  #   image: ghcr.io/rdemora2/back-site--tivix-performance-tracker:latest
  #   container_name: app-performance-tracker-backend
  #   ...

networks:
  web:
    external: true
  internal-services:
    external: true
